# Generated by Django 3.0.3 on 2020-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=264)),
                ('Second_Name', models.CharField(max_length=264)),
                ('E_mail', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
